### ISSUE TITLE
Move target output to session folder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [surfacepatterns/synthclone#16]
```
Putting output in the session directory makes creating targets easier to manage.

Reported by Gabbe Nord.
```

Original issue reported on code.google.com by `surfacep...@gmail.com` on 19 Feb 2013 at 5:35

**Comment by surfacepatterns** [comment]
This *seemed* like a good idea eight years ago, but, in hindsight (and with the perspective of how I want to change `synthclone` going forward), this was a poorly thought out idea.
