### ISSUE TITLE
Port synthclone to Qt 5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [surfacepatterns/synthclone#20]
```
Qt 5 is starting to be used as the standard Qt in some Linux distributions.  
synthclone should be ported at some point.
```

Original issue reported on code.google.com by `surfacep...@gmail.com` on 16 Sep 2013 at 1:53

**Comment by edogawa23** [comment]
I'm maintaining a RPM package for opnSUSE, and as they recently removed Qt4 from the distribution I naively attempted a Qt5 port and was able to at least make it compile and run, see #24 . I realize that the code hasn't seen updates in years, maybe we can at least avoid bitrot?

**Comment by trebmuh** [comment]
Nice to see that an effort has been put toward Qt5.
Thank you for that @edogawa23 !

**Comment by dromer** [comment]
@edogawa23 your PR seems to work fine, now just running into limitations of the software itself and a growing list of feature ideas ;)

**Comment by surfacepatterns** [comment]
Hi all.  Thank you so much for your efforts in porting `synthclone` to Qt5.  I'm glad folks were trying to keep `synthclone` alive all this time. :)

I've just finished porting `synthclone` to Qt6.  There are probably still quite a few bugs to discover - I never did write proper tests for any of the functionality in `synthclone`, and I don't seem to remember the samplers being as broken as they are now - but things are starting to work again.

Anyway, just a heads-up. :)
