### ISSUE TITLE
Compile problem Ubuntu 18.04

### ISSUE THREAD

**Issue by Taikakim** [surfacepatterns/synthclone#23]
kim@kim-desktop:~/Downloads/synthclone-master$   ./configure --prefix=/usr
Reading /home/kim/Downloads/synthclone-master/src/src.pro
 Reading /home/kim/Downloads/synthclone-master/src/lib/lib.pro
Project WARNING: CONFIG+=uitools is deprecated. Use QT+=uitools instead.
Project ERROR: Unknown module(s) in QT: uitools
Usage: configure [options] [qmake-args]

So, I guess there is some QT problem here? Anything I could try? I'm pretty new to Linux so I'm not sure what to do even here. Or is the source code just outdated for such a new distribution?

**Comment by dromer** [comment]
See https://github.com/surfacepatterns/synthclone/pull/24

**Comment by surfacepatterns** [comment]
Thanks for filing this bug five years ago.  I'm sorry it took me five years to get around to it. :(

I have `synthclone` compiling on Ubuntu 22.04 with Qt6 now.  I wouldn't be at all surprised if you've lost interest, but, if you happen to still be around and are still interested in the application, feel free to clone the repo and give it a go. :)

**Comment by surfacepatterns** [comment]
FTR, I'm compiling `synthclone` on Ubuntu 22.04 with Qt6 with:
```
./configure --debug --prefix=/usr --qmake='/usr/bin/qmake6'
make
```

**Comment by Taikakim** [comment]
Thanks, I didn't need this for a while, but now that I know it works, I might try this since it's a handy tool!

**Comment by dromer** [comment]
Latest Qt6 version isn't fully functional yet, but hopefully it will be soon!

**Comment by surfacepatterns** [comment]
> Latest Qt6 version isn't fully functional yet, but hopefully it will be soon!

@dromer: I'm absolutely sure there are more issues to find and I'm in the process of making time to do so.  In the meantime, if you could tell me what issues you're running into, it would help me to prioritize what to fix first. :)

**Comment by dromer** [comment]
@surfacepatterns sure! I'll create tickets as I run into stuff.
